-- Drop Indici
DROP INDEX idx_batch_job_instance_1;
DROP INDEX idx_batch_job_execution_1;
DROP INDEX idx_batch_step_execution_1;
DROP INDEX idx_batch_step_execution_2;

-- Drop Sequences if they exist
DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ CASCADE;
DROP SEQUENCE IF EXISTS BATCH_JOB_EXECUTION_SEQ CASCADE;
DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ CASCADE;

-- Drop Tables with CASCADE to remove foreign key references if they exist
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;