-- DROP TRIGGERS
DROP TRIGGER trg_batch_step_ex;
DROP TRIGGER trg_batch_job_ex;
DROP TRIGGER trg_batch_job;

-- Drop Sequences if they exist
DROP SEQUENCE BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE BATCH_JOB_SEQ;

-- Drop Tables with CASCADE to remove foreign key references if they exist
DROP TABLE BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE BATCH_STEP_EXECUTION;
DROP TABLE BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE BATCH_JOB_EXECUTION;
DROP TABLE BATCH_JOB_INSTANCE;