-- =============================================================================
-- Script di svecchiamento tabelle Spring Batch per HSQLDB
--
-- Elimina le esecuzioni di job completati (COMPLETED, FAILED, STOPPED, ABANDONED)
-- più vecchi di un numero configurabile di giorni.
--
-- Le cancellazioni rispettano l'ordine imposto dalle foreign key.
-- =============================================================================

-- Configurazione: numero di giorni di retention
-- Modifica il valore nella CALL sotto in base alle esigenze (default: 90 giorni)

-- 1. BATCH_STEP_EXECUTION_CONTEXT
DELETE FROM BATCH_STEP_EXECUTION_CONTEXT
WHERE STEP_EXECUTION_ID IN (
    SELECT se.STEP_EXECUTION_ID
    FROM BATCH_STEP_EXECUTION se
    JOIN BATCH_JOB_EXECUTION je ON se.JOB_EXECUTION_ID = je.JOB_EXECUTION_ID
    WHERE je.END_TIME < TIMESTAMPADD(SQL_TSI_DAY, -90, CURRENT_TIMESTAMP)
      AND je.STATUS IN ('COMPLETED', 'FAILED', 'STOPPED', 'ABANDONED')
);

-- 2. BATCH_STEP_EXECUTION
DELETE FROM BATCH_STEP_EXECUTION
WHERE JOB_EXECUTION_ID IN (
    SELECT JOB_EXECUTION_ID
    FROM BATCH_JOB_EXECUTION
    WHERE END_TIME < TIMESTAMPADD(SQL_TSI_DAY, -90, CURRENT_TIMESTAMP)
      AND STATUS IN ('COMPLETED', 'FAILED', 'STOPPED', 'ABANDONED')
);

-- 3. BATCH_JOB_EXECUTION_CONTEXT
DELETE FROM BATCH_JOB_EXECUTION_CONTEXT
WHERE JOB_EXECUTION_ID IN (
    SELECT JOB_EXECUTION_ID
    FROM BATCH_JOB_EXECUTION
    WHERE END_TIME < TIMESTAMPADD(SQL_TSI_DAY, -90, CURRENT_TIMESTAMP)
      AND STATUS IN ('COMPLETED', 'FAILED', 'STOPPED', 'ABANDONED')
);

-- 4. BATCH_JOB_EXECUTION_PARAMS
DELETE FROM BATCH_JOB_EXECUTION_PARAMS
WHERE JOB_EXECUTION_ID IN (
    SELECT JOB_EXECUTION_ID
    FROM BATCH_JOB_EXECUTION
    WHERE END_TIME < TIMESTAMPADD(SQL_TSI_DAY, -90, CURRENT_TIMESTAMP)
      AND STATUS IN ('COMPLETED', 'FAILED', 'STOPPED', 'ABANDONED')
);

-- 5. BATCH_JOB_EXECUTION
DELETE FROM BATCH_JOB_EXECUTION
WHERE END_TIME < TIMESTAMPADD(SQL_TSI_DAY, -90, CURRENT_TIMESTAMP)
  AND STATUS IN ('COMPLETED', 'FAILED', 'STOPPED', 'ABANDONED');

-- 6. BATCH_JOB_INSTANCE (solo se non hanno più esecuzioni associate)
DELETE FROM BATCH_JOB_INSTANCE
WHERE JOB_INSTANCE_ID NOT IN (
    SELECT DISTINCT JOB_INSTANCE_ID
    FROM BATCH_JOB_EXECUTION
);

COMMIT;
