-- Drop Sequences if they exist
DROP SEQUENCE BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE BATCH_JOB_SEQ;

-- Drop Tables with CASCADE to remove foreign key references if they exist
DROP TABLE BATCH_JOB_EXECUTION_CONTEXT CASCADE;
DROP TABLE BATCH_STEP_EXECUTION_CONTEXT CASCADE;
DROP TABLE BATCH_STEP_EXECUTION CASCADE;
DROP TABLE BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE BATCH_JOB_EXECUTION CASCADE;
DROP TABLE BATCH_JOB_INSTANCE;