# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'  # Trigger per tutti i tag 
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set timezone to Europe/Rome
      run: sudo timedatectl set-timezone Europe/Rome
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -P jar -DskipTests

    - name: Upload artifact to GitHub
      uses: actions/upload-artifact@v4.6.0
      with:
        name: govpay-aca-batch
        path: target/govpay-aca-batch.jar

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4.1.0
      with:
        token: ${{ secrets.GH_TOKEN }}
        
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GitHub release
      id: create_release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: target/govpay-aca-batch.jar  # Specifica l'artefatto da caricare
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 

        
        
